myapp:
  test:
    zhuhongmin
eureka:
  client:
    healthcheck:
      enabled: true

spring:
  redis:
    host: 192.168.246.222
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8

mybatis:
  type-aliases-package: com.valley.cloudservice.common.api.entity
  mapperLocations: classpath*:mybatis/mapper/**/*Mapper.xml